- name: Hello From Ansible #This is the first play
  hosts: local #make sure the same is repeated in Inventory
  connection: local
  tasks: 
  - name: Play-1 and Task-1
    ansible.builtin.debug:
      msg: Hello from play-1, Task-1

- name: Hello again From Ansible #This is the second play
  hosts: local
  connection: local
  tasks: 
  - name: Play-2 and Task-1
    ansible.builtin.debug:
      msg: Hello from play-2, Task-1