- name: Play-1 Started
  hosts: local
  connection: local
  vars:
    Number1: 10
  tasks:
  - name: Task 1 of Play 1 Started
    ansible.builtin.debug:
      msg: The Given Number is Greater than 10.
    when: Number1 > 10
  - name: Task 2 of Play 1 Started
    ansible.builtin.debug:
      msg: The Given Number is less than 10.
    when: Number1 < 10
  - name: Task 3 of Play 1 Started
    ansible.builtin.debug:
      msg: The Given Number is equal to 10.
    when: Number1 == 10