- name: Play-1 Started
  hosts: local
  connection: local
  vars_files:
  - VariablesFile.txt
  tasks: 
  - name: Task-1 of Play-1 Started
    ansible.builtin.debug:
      msg: Hello Printing Variables from a file. {{ var1 }},{{ var2 }}
