- name: Play-1 Starts
  hosts: local
  connection: local
  vars:
    course_name: DevSecOps with AWS
    course_Duration: 120
    is_it_free : false
    Topics_covered:
    - linux
    - shellScripting
    - Ansible(Running)
    Remaining_Topics:
      ci_cd: Jenkins
      scripting: Shell and Python
      Config_management: Ansible
      IAC: Terraform with AWS
      Containers: Docker
      Orchestration: K8s
  tasks:
  - name: Task-1 of Play-1 Starts
    ansible.builtin.debug:
      msg: CourseName-{{ course_name }}
  - name: Task-2 of Play-1 Starts
    ansible.builtin.debug:
      msg: CourseDuration:{{ course_Duration }}
  - name: Task-3 of Play-1 Starts
    ansible.builtin.debug:
      msg: Is It free-{{ is_it_free }}
  - name: Task-4 of Play-1 Starts
    ansible.builtin.debug:
      msg: Topics covered-{{ Topics_covered }}
  - name: Task-5 of Play-1 Starts
    ansible.builtin.debug:
      msg: Remaining Topics-{{ Remaining_Topics }}